Custom Domain HCL
PropelAuth/terraform-provider-propelauth pull request #5
Opened 2024-08-27 19:59 UTC by itailevi98

# Smoke Tests
  All smoke tests performed were completely managed through TF. No updates were made to the dashboard to check existing state. It is expected that all will be done in an empty TF state.

* With no verified prod realm, calling terraform plan/apply created a new unverified domain for sharpenchess.com. The verification, however, failed as there code was incorrect. 
* When updating the domain to sharpenchess2.com, the domain and txt code was updated as expected. The verification failed again as expected.
* When adding a subdomain, the subdomain was updated. The verification failed again as expected.
* When changing the domain back to sharpenchess.com and removing the subdomain, all was updated as expected. The verification failed again as expected.
* When changing the verification code manually in the DB to the correct one, and running `terraform apply`, the prod environment was verified successfully. 
* When running `terraform plan`, no changes were found, as expected.
* When changing the domain to `itailevi.com`, the state was updated to the new records and domain. The verification failed, as expected.
* When changing the subdomain to the pending prod env, the state was updated to add the new subdomain, and verification failed as expected.
* When removing the subdomain, the state was updated as expected, and the verification failed again.
* When updating the domain to a different one and back, all states were updated as expected, and all verifications failed.
* When changing the verification code manually in the DB to the correct one, and running `terraform apply`, the prod environment was switched successfully. 
* When changing the environment to "Staging" the resource was deleted and recreated to track staging environment.

2024-08-27 22:15 UTC, mrmauer reviewed
Only did a quick check so far but there's a few pieces we still need:
1. We need a timeout attribute on the `custom_domain_verification` resource to force a wait until whatever DNS provider has populated the TXT record. See docs on that [here](https://developer.hashicorp.com/terraform/plugin/framework/resources/timeouts#attribute).
2. [small thing] We should add a computed `realm_id`/`environment_id` attribute to the `custom_domain_verification` resource. This is effectively where prod/staging realms are created, and we'll likely need that realm_id for a variety of things later.

2024-08-28 15:10 UTC, itailevi98 commented
> [small thing] We should add a computed realm_id/environment_id attribute to the custom_domain_verification resource. This is effectively where prod/staging realms are created, and we'll likely need that realm_id for a variety of things later.

Is this something that is safe to include in the TF state? as far as i can tell, we don't really save ID's of things like realm ID or even project ID. Also curious what the later uses for having this are :)

2024-08-28 15:11 UTC, itailevi98 commented
Added the timeouts attribute -- I left it out since we don't currently rely on any DNS provider/resolver, but it didn't hurt to add it now.

2024-08-28 18:05 UTC, mrmauer commented
> > [small thing] We should add a computed realm_id/environment_id attribute to the custom_domain_verification resource. This is effectively where prod/staging realms are created, and we'll likely need that realm_id for a variety of things later.
> 
> Is this something that is safe to include in the TF state? as far as i can tell, we don't really save ID's of things like realm ID or even project ID. Also curious what the later uses for having this are :)

We do actually store the project ID on the provider. I'm not so worried about storing realm IDs in the TF state. Tho I'm also cool w/ just not including it until we find we need it. There are plenty of actions/configurations that are realm-specific (eg require_email_confirmation, allow_public_signups, FE integration, BE integration, and BE api keys), though the `environment = "Test" | "Staging" | "Prod"` method seems to work fine for now. We just need a mechanism for resources specific to a prod/staging realm to be dependent on this domain verification resource -- which can be accomplished by the built-in `depends_on` attribute.

2024-09-04 14:32 UTC, mrmauer commented on internal/provider/custom_domain_resource.go
> +	tflog.Trace(ctx, "created a propelauth_project_info resource")
need to update this log line from `project_info`

2024-09-04 14:42 UTC, mrmauer commented on examples/resources/custom_domain/main.tf
> +    # }
let's clean up this example and it's comments, so it provides a clear guide on how to us our provider w/ a dns provider

2024-09-04 14:44 UTC, mrmauer commented on internal/provider/custom_domain_resource.go
> +	customDomainInfo, err := r.client.GetCustomDomainInfo(state.Environment.ValueString(), false)
since the `environment` attribute requires replace, we can just use the plan for this

2024-09-04 15:12 UTC, mrmauer commented on internal/provider/custom_domain_verification_resource.go
> +	verificationErr := r.client.VerifyCustomDomainInfo(environment, false)
Here we need to leverage the timeout created above. We should add some logic that parses out the specific error_code that indicates the TXT/CNAME record was not found (which likely means the DNS provider hasn't finished propagating it) and retries verification at intervals for the duration of the timeout.

2024-09-04 15:15 UTC, mrmauer commented on internal/provider/provider_test.go
> +   api_key = "c557308180b7da18d7e0e9cbd2ae3b36833c0165b5158c439efe59662df01701c2e23b00211b9c25b5223e51417f323b"
Luckily there are only credentials for a local development instance of the config service, but we need to be careful not to commit these. Exporting these values to environment variables (directly or from a script) should be enough that we don't need to edit this file.

2024-09-04 15:17 UTC, mrmauer requested changes
A few nits and then some changes around timeouts to make this work with the delays involved w/ a live DNS provider.

2024-09-05 14:19 UTC, mrmauer commented on internal/provider/custom_domain_resource.go
> +	tflog.Trace(ctx, "created a propelauth_project_info resource")
```suggestion
	tflog.Trace(ctx, "created a propelauth_custom_domain resource")
```

2024-09-05 14:20 UTC, mrmauer commented on internal/provider/custom_domain_resource.go
> +	tflog.Trace(ctx, "updated a custom_domain resource")
```suggestion
	tflog.Trace(ctx, "updated a propelauth_custom_domain resource")
```

2024-09-05 14:21 UTC, mrmauer commented on internal/provider/custom_domain_resource.go
> +	tflog.Trace(ctx, "deleted a custom_domain resource")
```suggestion
	tflog.Trace(ctx, "deleted a propelauth_custom_domain resource")
```

2024-09-05 14:27 UTC, mrmauer commented on internal/provider/provider_test.go
> +   api_key = "c557308180b7da18d7e0e9cbd2ae3b36833c0165b5158c439efe59662df01701c2e23b00211b9c25b5223e51417f323b"
```suggestion
#   tenant_id = "<PROPELAUTH_TENANT_ID>"
#   project_id = "<PROPELAUTH_PROJECT_ID>"
#   api_key = "<PROPELAUTH_API_KEY>"
```

2024-09-05 14:28 UTC, mrmauer commented on examples/resources/custom_domain/main.tf
> +    # }
I'll own cleaning this up and formatting it for docs generation in [this adjacent PR](https://github.com/PropelAuth/terraform-provider-propelauth/pull/7/files).

2024-09-05 14:35 UTC, mrmauer submitted a review, later dismissed
Tested and working w/ a live DNS provider and timeouts, fixed a few small items, and the example clean up will be handled elsewhere

2024-09-05 15:26 UTC, mrmauer approved these changes
lgtm. 
Examples clean up, docs generation, and otherCI checks will happen on another PR.

2024-09-05 15:27 UTC, merged